version: "3"

services:
  server:
    build: calculator_client/
    ports:
      - "50051:50051"

  client:
    build: calculator_server/
    network_mode: host
    depends_on:
      - server
